# -*- coding: utf-8 -*-
"""Week2-Assignment- Questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/svkarthik86/Fundamentals-of-statistics-and-probability/blob/main/Week2-Assignment-%20Questions.ipynb

### WEEK-2: Assignment  - Probability Distribution

### 1.Calculate Probabilities Using a Binomial Distribution

Q1.1. Pavan kumar makes 65% of his free-throw attempts. If he shoots 15 free throws, what is the probability that he makes exactly 10?
"""

from scipy.stats import binom
binom.pmf(k=10,n=15,p=0.65)

"""Q1.2.Shivam flips a fair coin 6 times. What is the probability that the coin lands on heads 3 times or fewer?"""

from scipy.stats import binom
binom.cdf(k=3,n=6,p=0.5)

"""Q1.3.It is known that 65% of individuals support a certain law. If 10 individuals are randomly selected, what is the probability that between 3 and 6 of them support the law?"""

from scipy.stats import binom
binom.cdf(k=6,n=10,p=0.65)-binom.cdf(k=3,n=10,p=0.61)

"""### 2.Calculate Probabilities Using a Poisson Distribution

Q2.1. A store sells 4 apples per day on average. What is the probability that they will sell 6 apples on a given day?
"""

from scipy.stats import poisson
poisson.pmf(6,4)

"""Q2.2. A certain store sells seven footballs per day on average. What is the probability that this store sells four or less footballs in a given day?"""

from scipy.stats import poisson
poisson.cdf(4,7)

"""Q2.3. A certain store sells 15 cans of tuna per day on average. What is the probability that this store sells more than 20 cans of tuna in a given day?"""

from scipy.stats import poisson
poisson.cdf(20,15)

prob_more_than_7=1- poisson.cdf(20,15)
prob_more_than_7

"""### 3.Calculate Probabilities Using a Uniform Distribution

Q3.1. Suppose a bus shows up at a bus stop every 20 minutes. If you arrive at the bus stop, what is the probability that the bus will show up in 8 minutes or less?
"""

from scipy.stats import uniform
uniform.cdf(x=8,loc=0,scale=20)-uniform.cdf(x=0,loc=0,scale=20)

"""Q3.2.The weight of a certain species of frog is uniformly distributed between 15 and 25 grams. If you randomly select a frog, what is the probability that the frog weighs between 17 and 19 grams?"""

from scipy.stats import uniform
uniform.cdf(x=19,loc=15,scale=10)-uniform.cdf(x=17,loc=15,scale=10)

"""Q3.3.The length of an NBA game is uniformly distributed between 120 and 170 minutes. What is the probability that a randomly selected NBA game lasts more than 150 minutes?"""

from scipy.stats import uniform
uniform.cdf(x=150,loc=120,scale=50)

prob_more_than_150=1- uniform.cdf(x=150,loc=120,scale=50)
prob_more_than_150

"""### 4.Calculate Probabilities Using a Normal Distribution

Q4.1.A radar unit is used to measure speeds of cars on a motorway. The speeds are normally distributed with a mean of 90 km/hr and a standard deviation of 10 km/hr. What is the probability that a car picked at random is travelling at more than 100 km/hr?
"""

from scipy.stats import norm
1-norm.cdf(100,90,10)

"""Q4.2.For a certain type of computers, the length of time bewteen charges of the battery is normally distributed with a mean of 50 hours and a standard deviation of 15 hours. John owns one of these computers and wants to know the probability that the length of time will be between 50 and 70 hours."""

from scipy.stats import norm
norm.cdf(70,50,15)-norm.cdf(50,50,15)

"""
Q4.3.Entry to a certain University is determined by a national test. The scores on this test are normally distributed with a mean of 500 and a standard deviation of 100. Tom wants to be admitted to this university and he knows that he must score better than at least 70% of the students who took the test. Tom takes the test and scores 585. Will he be admitted to this university?"""

from scipy.stats import norm
norm.cdf(585,500,100)

